"""P16–P20: deterministic manuscript composition.

Origin policy: these sections are generated by Paper Factory code from the
claim graph, metrics and evidence ledger — template prose with macro-filled
numbers. Backend identity = {"family": "deterministic"}; marking n/a. The
firewall is consulted before every write; origin receipts are recorded.
An optional LLM polish layer may replace sections later — only through the
provider router under the same policy.
"""
from __future__ import annotations

import json
from pathlib import Path

from ..core.config import MarkingRegistry, ProviderPolicyConfig
from ..core.results import Verdict
from ..core.util import utcnow, write_json
from ..dag.executor import NodeContext, NodeOutcome
from ..provenance.firewall import decide_write
from ..provenance.origin import record_origin

DETERMINISTIC_BACKEND = {
    "provider_family": "paper-factory",
    "family": "deterministic",
    "model_family": "deterministic",
    "model": "template-generator",
    "marking_status": "not_applicable",
}

SECTION_ORDER = ["methods", "results", "introduction", "discussion", "abstract"]


def _macro_for(metrics: dict, suffix: str = "") -> str | None:
    keys = [k for k in metrics.get("metrics", {}) if "fpr" in k.lower()]
    return keys[0] if keys else None


def _compose_section(section: str, ctx: NodeContext) -> str:
    ws = ctx.workspace
    metrics_path = ws.reports_dir / "paper_metrics.json"
    metrics = json.loads(metrics_path.read_text()) if metrics_path.exists() else {}
    claims_path = ws.claims_dir / "claims.yaml"
    claims = []
    if claims_path.exists():
        import yaml

        claims = (yaml.safe_load(claims_path.read_text()) or {}).get("claims", [])
    verified = [c for c in claims if c.get("status") in ("VERIFIED", "EVIDENCE_FOUND")]

    if section == "methods":
        return ("\\section{Methods}\n\\label{sec:methods}\n"
                "All experiments were executed deterministically with fixed seeds. "
                "Raw artifacts, analysis scripts and result files were hashed at intake "
                "(T0 evidence). All reported numbers derive from \\texttt{generated/numbers.tex}, "
                "produced by the statistics pipeline; no value was entered by hand.\n")
    if section == "results":
        tab_ref = None
        tm = ws.reports_dir / "tables_manifest.json"
        if tm.exists():
            tables = json.loads(tm.read_text()).get("tables", [])
            if tables:
                tab_ref = tables[0].get("label")
        intro = ("The generated tables and figures summarise the measured outcomes."
                 if not tab_ref else
                 f"Table~\\ref{{{tab_ref}}} and the generated figures summarise the "
                 "measured outcomes.")
        lines = ["\\section{Results}", "\\label{sec:results}", intro]
        for key, m in list(metrics.get("metrics", {}).items())[:8]:
            safe = key.replace("_", "")
            shown = key.replace("_", "\\_")
            lines.append(f"For \\texttt{{{shown}}} we measured a mean of "
                         f"$\\pfget{{{safe}mean}}$ (n=$\\pfget{{{safe}n}}$).")
        if not metrics.get("metrics"):
            lines.append("% no metrics available — results section stays empty rather than invented")
        return "\n".join(lines) + "\n"
    if section == "introduction":
        return ("\\section{Introduction}\n\\label{sec:introduction}\n"
                "This work was produced by an evidence-first pipeline: every empirical claim "
                "is linked to hashed artifacts, and citations were verified against Crossref "
                "and OpenAlex before inclusion.\n")
    if section == "discussion":
        lines = ["\\section{Discussion and Limitations}", "\\label{sec:discussion}"]
        small = metrics.get("audit", {}).get("small_samples", [])
        if small:
            shown = ", ".join(s.replace("_", "\\_") for s in small[:6])
            lines.append(f"Sample sizes are small for \\texttt{{{shown}}}; "
                         "we therefore report descriptive statistics only and make no "
                         "significance claims.")
        lines.append("Claims that no artifact could carry were retired before freeze; "
                     "the claim ledger records the retirements.")
        return "\n".join(lines) + "\n"
    if section == "abstract":
        return (f"We report a fully reproducible study. "
                f"{len(verified)} empirical claims survived evidence linkage; all numbers "
                "in this paper are generated from the underlying artifacts.\n")
    raise ValueError(section)


def run_section_compose(ctx: NodeContext, section: str) -> NodeOutcome:
    ws = ctx.workspace
    sections_dir = ws.paper_dir / "sections"
    sections_dir.mkdir(parents=True, exist_ok=True)
    target = sections_dir / f"{section}.tex"
    rel = f"paper/sections/{section}.tex"

    decide_write(rel, role="manuscript_writer", backend=DETERMINISTIC_BACKEND,
                 policy=ctx.policy, marking=ctx.marking)  # raises PolicyViolation on denial

    text = _compose_section(section, ctx)
    if target.exists() and target.read_text(encoding="utf-8") == text:
        pass  # idempotent
    else:
        target.write_text(text, encoding="utf-8")
    record_origin(ws, rel_path=rel, abs_path=target, role="manuscript_writer",
                  backend=DETERMINISTIC_BACKEND, run_id=ctx.run_id, node_id=f"P-{section}",
                  invocation_receipt=None)
    return NodeOutcome(Verdict.PASS, {"section": section, "bytes": len(text)})


def make_section_handler(section: str):
    def handler(ctx: NodeContext) -> NodeOutcome:
        return run_section_compose(ctx, section)

    return handler


def run_finalize_main(ctx: NodeContext) -> NodeOutcome:
    """Replace <<PF:title>>/<<PF:authors>>/<<PF:date>> in main.tex; the file is
    protected — the firewall is consulted and an origin receipt recorded."""
    ws = ctx.workspace
    main = ws.paper_dir / "main.tex"
    if not main.exists():
        return NodeOutcome(Verdict.FAIL, {"reason": "main.tex missing (P15 must run first)"})
    decision = decide_write("paper/main.tex", role="manuscript_writer",
                            backend=DETERMINISTIC_BACKEND, policy=ctx.policy,
                            marking=ctx.marking)
    if not decision.allowed:
        return NodeOutcome(Verdict.FAIL, {"reason": decision.reason})
    text = main.read_text(encoding="utf-8")
    title = ctx.config.paper.title or ws.target_root.name.replace("_", " ").title()
    text = (text.replace("<<PF:title>>", title)
                .replace("<<PF:authors>>", "Paper Factory Pipeline (evidence-first)")
                .replace("<<PF:date>>", utcnow()[:10]))
    main.write_text(text, encoding="utf-8")
    record_origin(ws, rel_path="paper/main.tex", abs_path=main, role="manuscript_writer",
                  backend=DETERMINISTIC_BACKEND, run_id=ctx.run_id, node_id="P20")
    remaining = any("<<PF:" in line for line in text.splitlines()
                    if not line.lstrip().startswith("%"))
    return NodeOutcome(Verdict.PASS if not remaining else Verdict.DEGRADED,
                       {"finalized": True, "placeholders_remaining": remaining})
