"""Standalone TikZ system-diagram generator (DeepSeek-style look).

A diagram is a plain dict spec: titled nodes with styled lines, arrows,
optional dashed cluster frames, and annotation/note boxes. ``render_diagram``
emits a standalone .tex (mathptmx to match the host document fonts) and
compiles it with pdflatex. Compile failures raise ``TikZCompileError`` with
the pdflatex log tail — never a silent fallback.
"""
from __future__ import annotations

import shutil
import subprocess
from pathlib import Path
from typing import Any

TIKZ_PREAMBLE = r"""% Auto-generated by paper_factory.figures.tikz_diagrams — do not hand-edit.
\documentclass[border=8pt]{standalone}
\usepackage[T1]{fontenc}
\usepackage{mathptmx}
\usepackage{tikz}
\usetikzlibrary{arrows.meta,positioning,fit,backgrounds}
\definecolor{pfdeep}{RGB}{27,58,75}    % dark navy — headings
\definecolor{pfaccent}{RGB}{44,122,122} % deep teal — emphasis
\definecolor{pffill}{RGB}{233,242,246}  % pastel box fill
\definecolor{pfgray}{RGB}{110,110,110}  % muted body text
\definecolor{pfcluster}{RGB}{150,170,180}
\tikzset{
  pfnode/.style={draw=pfaccent, fill=pffill, rounded corners=3pt,
                 line width=1pt, inner sep=7pt, align=center,
                 font=\small, text=pfdeep},
  pfnote/.style={draw=pfcluster, fill=white, rounded corners=3pt,
                 line width=0.7pt, inner sep=10pt, align=left,
                 font=\small, text=pfdeep},
  pfcluster/.style={draw=pfcluster, dashed, rounded corners=6pt,
                    line width=0.8pt, inner sep=10pt},
  pfarrow/.style={-{Stealth[length=3mm,width=2.2mm]}, line width=1.1pt,
                  draw=pfaccent},
}
"""


class TikZCompileError(RuntimeError):
    """pdflatex failed on a generated diagram; carries the log tail."""


def _tex_escape(text: str) -> str:
    return (text.replace("\\", r"\textbackslash{}")
                .replace("&", r"\&").replace("%", r"\%")
                .replace("#", r"\#").replace("_", r"\_"))


_LINE_STYLES = {
    "plain": "",
    "teal": r"\color{pfaccent}\bfseries ",
    "bold": r"\bfseries ",
    "gray": r"\color{pfgray} ",
    "grayit": r"\color{pfgray}\itshape ",
    "big": r"\color{pfaccent}\bfseries\large ",
}


def _line_tex(line: dict[str, Any]) -> str:
    style = _LINE_STYLES.get(line.get("style", "plain"), "")
    text = line["text"]
    if not line.get("raw", False):
        text = _tex_escape(text)
    body = f"{{{style}{text}}}" if style else f"{{{text}}}"
    if line.get("style") == "big":
        return body
    return r"\par\smallskip" + "\n" + body if line.get("skip_before") else body


def _node_tex(node: dict[str, Any]) -> str:
    style = node.get("style", "pfnode")
    title = node["title"]
    if not node.get("raw_title", False):
        title = _tex_escape(title)
    parts: list[str] = []
    if title:
        parts.append(r"{\bfseries\color{pfdeep} " + title + "}")
    for ln in node.get("lines", []):
        if parts:
            parts.append(r"\par\smallskip")
        parts.append(_line_tex(ln))
    inner = "\n".join(parts)
    opts = [style]
    if node.get("text_width"):
        opts.append(f"text width={node['text_width']}")
    if node.get("minimum_height"):
        opts.append(f"minimum height={node['minimum_height']}")
    return (f"\\node[{', '.join(opts)}] ({node['id']}) at {node['pos']}\n"
            f"{{{inner}}};")


def spec_to_tex(spec: dict[str, Any]) -> str:
    body: list[str] = [r"\begin{document}", r"\begin{tikzpicture}",
                       r"\sffamily"]
    title = spec.get("title")
    if title:
        body.append(
            r"\node[anchor=west, font=\Large\bfseries, text=pfdeep] (pfTitle) at "
            + spec.get("title_pos", "(0,0)")
            + f"\n{{{_tex_escape(title)}}};")

    # Optional dashed cluster frames: fit around listed node ids.
    for cl in spec.get("clusters", []):
        body.append(
            r"\begin{scope}[on background layer]"
            "\n" + r"\node[pfcluster" +
            (f", label={{[pfgray]above:{_tex_escape(cl['label'])}}}"
             if cl.get("label") else "") +
            f"] ({cl['id']}) fit ("
            + ") (".join(cl["nodes"]) + ");\n"
            r"\end{scope}")

    for node in spec.get("nodes", []):
        body.append(_node_tex(node))

    for arrow in spec.get("arrows", []):
        if len(arrow) == 2:
            src, dst = arrow
            opts = "pfarrow"
        else:
            src, dst, extra = arrow
            opts = f"pfarrow, {extra}"
        body.append(f"\\draw[{opts}] ({src}) -- ({dst});")

    for ann in spec.get("annotations", []):
        # free text block: {pos, text, width, style, font}
        opts = [ann.get("style", "font=\\small, text=pfdeep, align=left")]
        if ann.get("width"):
            opts.append(f"text width={ann['width']}")
        body.append(f"\\node[anchor=north west, {', '.join(opts)}] at {ann['pos']}\n"
                    f"{{{ann['text']}}};")

    body.append(r"\end{tikzpicture}")
    body.append(r"\end{document}")
    return TIKZ_PREAMBLE + "\n".join(body) + "\n"


def render_diagram(spec: dict[str, Any], out_dir: Path | str, name: str,
                   timeout: int = 120) -> dict[str, Any]:
    """Write <name>.tex for spec and compile to PDF with pdflatex.

    Returns {"tex": Path, "pdf": Path}. Raises TikZCompileError with the
    pdflatex log tail on any failure — never a silent fallback."""
    out = Path(out_dir)
    out.mkdir(parents=True, exist_ok=True)
    if not shutil.which("pdflatex"):
        raise TikZCompileError("pdflatex not found on PATH")
    tex_path = out / f"{name}.tex"
    tex_path.write_text(spec_to_tex(spec), encoding="utf-8")
    proc = subprocess.run(
        ["pdflatex", "-interaction=nonstopmode", "-halt-on-error",
         f"-jobname={name}", tex_path.name],
        cwd=out, capture_output=True, text=True, timeout=timeout)
    log_path = out / f"{name}.log"
    log_tail = "\n".join((log_path.read_text(errors="replace") if log_path.exists()
                          else proc.stdout).splitlines()[-40:])
    pdf_path = out / f"{name}.pdf"
    if proc.returncode != 0 or not pdf_path.exists() or pdf_path.stat().st_size == 0:
        raise TikZCompileError(
            f"pdflatex failed for {tex_path} (rc={proc.returncode})\n"
            f"--- log tail ---\n{log_tail}")
    return {"tex": tex_path, "pdf": pdf_path}


# ---------------------------------------------------------------------------
# Pilot 3 (massinv paper 1) diagram specs — numbers transcribed verbatim from
# pilots/pilot-03-massinv-paper1/project/draft/fig{1,2}_*.png (read-only refs).
# ---------------------------------------------------------------------------

def pilot3_fig1_event_model_spec() -> dict[str, Any]:
    """Fig 1: operational participation as distinct, claim-relevant events."""
    chain_y = "(0,0)"
    chain: list[dict[str, Any]] = []
    xs = ["(0,0)", "(3.3,0)", "(6.6,0)", "(10.4,0)", "(14.2,0)", "(17.6,0)"]
    events = [
        ("evS", "Stored", "S"),
        ("evG", "Graph-present", "G"),
        ("evX", "Executed", "X(W)"),
        ("evR", "Gradient /\\\\regularization", "R\\_grad / R\\_reg"),
        ("evU", "Update-\\\\reachable", "R\\_upd"),
        ("evM", "Moved", "M(W,$\\tau$)"),
    ]
    widths = ["2.1cm", "2.1cm", "2.1cm", "2.5cm", "2.1cm", "2.1cm"]
    for (nid, title, sub), pos, tw in zip(events, xs, widths):
        chain.append({
            "id": nid, "pos": pos,
            "title": title, "raw_title": True,
            "lines": [{"text": sub, "raw": True, "style": "gray"}],
            "text_width": tw, "minimum_height": "1.5cm",
        })
    arrows = [("evS", "evG"), ("evG", "evX"), ("evX", "evR"),
              ("evR", "evU"), ("evU", "evM")]
    return {
        "title": "Operational participation is measured as distinct, "
                 "claim-relevant events",
        "title_pos": "(0,2.6)",
        "nodes": chain + [
            {"id": "guardrail", "pos": "(0,-3.9)", "style": "pfnote",
             "text_width": "8.6cm", "minimum_height": "2.6cm",
             "title": "Interpretation guardrail",
             "lines": [
                 {"text": "Structural reachability arithmetic is not an "
                          "empirical finite-window gradient-union estimate."},
                 {"text": "A different cadence, horizon, width, seed, or "
                          "data order may change the reachable set."},
             ]},
            {"id": "audited", "pos": "(10.4,-3.9)", "style": "pfnote",
             "text_width": "7.6cm", "minimum_height": "2.6cm",
             "title": "Audited d3072/L24/r6 case",
             "lines": [
                 {"text": "766,771,200 / 1,020,057,600", "style": "big",
                  "skip_before": True},
                 {"text": "scalar coordinates classified as structurally "
                          "raw-gradient-unreachable (75.17%)"},
             ]},
        ],
        "arrows": arrows,
        "annotations": [
            {"pos": "(0,-1.9)",
             "text": r"{Predicates are indexed by the declared observation "
                     r"window $W$ and must be observed or justified at the "
                     r"claim-relevant scope.}",
             "width": "16.5cm", "style": "font=\\small, text=pfgray"},
        ],
    }


def pilot3_fig2_attribution_spec() -> dict[str, Any]:
    """Fig 2: parameter-local ownership and final internal attestation."""
    box = {"style": "pfnode", "minimum_height": "3.2cm"}
    return {
        "title": "Parameter-local ownership and final internal attestation",
        "title_pos": "(0,2.2)",
        "nodes": [
            {"id": "hist", "pos": "(0,0)", "text_width": "4.6cm", **box,
             "title": "Historical MMAV path",
             "lines": [
                 {"text": "Target gate scope: 168 tensors"},
                 {"text": "Muon-owned target tensors: 0", "style": "teal"},
                 {"text": "Target FFN matrices followed the auxiliary "
                          "AdamW path."},
             ]},
            {"id": "armA", "pos": "(6.3,0)", "text_width": "4.6cm", **box,
             "title": "Corrected arm A",
             "lines": [
                 {"text": "Gate scope: 168 target tensors"},
                 {"text": "Explicit Muon path: 72 target matrices",
                  "style": "teal"},
                 {"text": "Arms B and C assign zero target matrices to the "
                          "Muon path."},
             ]},
            {"id": "sweep", "pos": "(12.6,0)", "text_width": "4.6cm", **box,
             "title": "Final attestation sweep",
             "lines": [
                 {"text": "19 attested artifacts"},
                 {"text": "7 direct GREEN + 12 exact", "style": "teal"},
                 {"text": "cadence signatures", "style": "gray"},
                 {"text": "0 artifacts classified INVALID."},
             ]},
        ],
        "arrows": [("hist", "armA"), ("armA", "sweep")],
        "annotations": [
            {"pos": "(0,-3.1)",
             "text": r"{\bfseries\color{pfdeep} Interpretation}"
                     r"\par\smallskip Run-level optimizer labels are not "
                     r"sufficient evidence for the claim-relevant parameter "
                     r"scope. Ownership must be reconciled with runtime "
                     r"manifests, update semantics, and artifact identity.",
             "width": "16.8cm"},
            {"pos": "(0,-5.6)",
             "text": r"\color{pfgray}\itshape The counts refer to different "
                     r"audit objects and are not classifier-accuracy "
                     r"estimates or a common-denominator performance "
                     r"comparison.",
             "width": "16.8cm"},
        ],
    }


def render_pilot3_diagrams(out_dir: Path | str) -> dict[str, dict[str, Any]]:
    """Render both pilot-03 diagrams (event model, attribution/attestation)."""
    return {stem: render_diagram(spec(), out_dir, stem)
            for stem, spec in KNOWN_SPECS.items()}


#: figure-stem → spec factory; latex_render upgrades raster figures with a
#: known spec to vector TikZ PDFs (same transcribed content)
KNOWN_SPECS = {
    "fig1_event_model": None,  # bound below (definition order)
    "fig2_attribution_attestation": None,
}
KNOWN_SPECS["fig1_event_model"] = pilot3_fig1_event_model_spec
KNOWN_SPECS["fig2_attribution_attestation"] = pilot3_fig2_attribution_spec
