"""Nextflow backend adapter for Reproduction Capsules (v1.4 WP-B).

Thin adapter behind the same Capsule -> Receipt contract as the WP5 local
runner and the WP7 Snakemake adapter. It generates ONE minimal main.nf in a
private run directory (never inside the caller's capsule directory),
executes it with `nextflow run`, and maps the result to an ExecutionReceipt
whose backend identity is `external/nextflow/<version>`. No Nextflow
semantics enter the core contract — the adapter maps, it does not
orchestrate, and Nextflow is never PF's orchestrator.

Design decisions (all fail-visible, none of them hidden):

- Capability honesty: if no `nextflow` binary is found (PATH, then the
  interpreter's own bin directory, then PF's own tools directory), `run`
  raises NextflowUnavailableError. There is no fake/partial mode.
- Staging: identical rationale as the Snakemake adapter — the capsule root
  is copied into the run directory and nextflow launches from there, so the
  caller's tree never sees `.nextflow*` metadata or the `work/` directory.
- One process per capsule. The generated main.nf declares exactly one
  `process capsule_run` whose script block cds into the staged
  `capsule_root / cwd` and runs exactly the capsule's command: argv is
  shlex-quoted and then escaped for the Groovy GString layer (`$`, `\\`),
  so Groovy interpolation cannot alter it and bash receives the capsule's
  bytes verbatim (review MAJOR-1 B; `\"\"\"`-containing argv is rejected
  fail-visible, not silently truncated). The process
  declares NO output block: output evidence is PF's own post-hoc hash
  collection (same as the local runner), not the workflow engine's. This
  is deliberate — it keeps receipt semantics identical across backends
  (see the partial-outputs conformance case: post-hoc collection records
  what exists instead of the wrapper failing the job).
- Process reaping on timeout/interrupt (review MAJOR-2 B): the wrapper
  runs in its own session and the whole group is SIGKILLed first.
  Nextflow's local executor can start a task OUTSIDE that group, so any
  process whose cmdline or cwd provably places it inside this run
  directory is then reaped via a /proc walk (strictly path-scoped — never
  foreign processes). This is best-effort by design: a task that detached
  AND left the run dir cannot be attributed and may survive; that hard
  limit is documented here instead of being claimed away. Pipe drainage
  after the kill is bounded, too — if non-PF processes hold the inherited
  pipes, the receipt records the capture as incomplete rather than
  hanging forever.
- `.nextflow*` paths are the backend's own bookkeeping and are pruned from
  the undeclared-output snapshot, exactly like `.snakemake` in the WP7
  adapter. Files the JOB writes outside expected_outputs are still flagged.
- Same documented hard limits as the other runners: this is not a sandbox.
"""
from __future__ import annotations

import os
import re
import shlex
import shutil
import signal
import subprocess
import sys
import tempfile
import uuid
from hashlib import sha256
from pathlib import Path

from ..verification.contract import BackendIdentity
from .capsule import ExecutionReceipt, ReproductionCapsule, utcnow
from .runner import LocalReproductionRunner

_MAIN_NF_HEADER = (
    "// Generated by paper_factory.reproduction.nextflow_backend (WP-B).\n"
    "// One process per ReproductionCapsule; do not edit by hand.\n"
)

# Grace period for the bounded pipe drain after a kill (review MAJOR-2 B):
# grandchildren that are NOT provably PF-owned can hold the inherited pipe
# ends open forever; after this many seconds the pipes are closed and the
# receipt records the capture as incomplete instead of hanging.
_DRAIN_GRACE = 10.0


class NextflowUnavailableError(RuntimeError):
    """No nextflow binary found (PATH, interpreter bin dir, PF tools dir).
    Fail-visible."""


def nextflow_binary() -> str | None:
    """Resolve a nextflow executable, or None if unavailable.

    Honest capability probe, same convention as the Snakemake adapter:
    PATH first, then the bin directory of the running interpreter (a
    nextflow launcher installed into PF's own venv is found even when the
    venv's bin dir is not on PATH), then PF's own tools directory
    (`<repo root>/tools/nextflow`, the documented install location for the
    get.nextflow.io launcher)."""
    found = shutil.which("nextflow")
    if found:
        return found
    candidate = Path(sys.executable).parent / "nextflow"
    if candidate.is_file():
        return str(candidate)
    tools_candidate = Path(__file__).resolve().parents[3] / "tools" / "nextflow"
    return str(tools_candidate) if tools_candidate.is_file() else None


def _nextflow_version(binary: str) -> str:
    proc = subprocess.run([binary, "-version"], capture_output=True,
                          timeout=60, check=False)
    blob = (proc.stdout + proc.stderr).decode("utf-8", "replace")
    match = re.search(r"version\s+(\d+\.\d+\.\d+)", blob)
    return match.group(1) if match else "unknown"


def _groovy_dquote_escape(text: str) -> str:
    """Escape text for embedding in a Groovy ``\"\"\"`` GString (Nextflow's
    `script` block is one).

    Nextflow interpolates `$var`/`${var}` itself, before bash ever sees the
    script, and `\\` starts a Groovy escape sequence — both silently corrupt
    capsule argv (reproduced, review MAJOR-1 B: `price$100` arrived as
    `price00` while the receipt claimed completed). Escaping happens AFTER
    shlex quoting and only at the Groovy layer: the backslashes are consumed
    when Nextflow parses the GString, so the bash-level string is byte-
    identical to the capsule's argv. Backslash first, then dollar, so the
    backslash just introduced for `\\$` is not doubled."""
    return text.replace("\\", "\\\\").replace("$", "\\$")


def render_nextflow_script(capsule: ReproductionCapsule,
                           staged_workdir: Path) -> str:
    """Deterministic minimal main.nf for one capsule.

    `staged_workdir` is the absolute path of `staged capsule root / cwd`
    inside the backend's private run directory (runtime scratch, never a
    committed file — embedding it is what reproduces the local runner's
    working-directory semantics). The process declares no outputs; PF
    collects output evidence itself after the run.

    Fail-visible limits (review MAJOR-1 B): an argv element containing
    `\"\"\"` would terminate the Groovy script block early and run a
    truncated command with a `completed` receipt — it is rejected with a
    clear error instead. `$` and `\\` in argv (and in the staged path) are
    escaped for the Groovy layer only, so the job receives the capsule's
    exact command."""
    if any('"""' in arg for arg in capsule.command):
        raise ValueError(
            'capsule command argument contains \'"""\', which would '
            "terminate the generated main.nf Groovy script block early and "
            "run a truncated command with a completed receipt — refusing "
            "to render (fail-visible; see "
            "docs/reports/DEFERRED_HARDENING.md)")
    shell_cmd = " ".join(shlex.quote(a) for a in capsule.command)
    script_block = "\n".join(
        f"    {_groovy_dquote_escape(line)}" for line in (
            "set -e",
            f"cd {shlex.quote(str(Path(staged_workdir).resolve()))}",
            f"{shell_cmd}",
        ))
    lines = [
        _MAIN_NF_HEADER.rstrip("\n"),
        "process capsule_run {",
        "    script:",
        '    """',
        script_block,
        '    """',
        "}",
        "",
        "workflow {",
        "    capsule_run()",
        "}",
        "",
    ]
    return "\n".join(lines)


def run_owned_pids(run_path: Path) -> list[int]:
    """PIDs whose cmdline or cwd provably places them inside this run
    directory. Linux /proc walk; empty list elsewhere or on any error.

    Attribution is deliberately strict (path-equality or path-under, never
    bare substring — sibling dirs like ``run2`` must not match ``run``):
    PF reaps only what belongs to its own run, never foreign processes."""
    run_str = str(run_path)
    prefix = run_str + os.sep
    proc_root = Path("/proc")
    if not proc_root.is_dir():
        return []
    pids: list[int] = []
    me = os.getpid()
    for entry in proc_root.iterdir():
        if not entry.name.isdigit():
            continue
        pid = int(entry.name)
        if pid == me:
            continue
        try:
            cwd = os.readlink(entry / "cwd")
        except OSError:
            cwd = ""
        if cwd == run_str or cwd.startswith(prefix):
            pids.append(pid)
            continue
        try:
            tokens = (entry / "cmdline").read_bytes().split(b"\0")
        except OSError:
            continue
        for token in tokens:
            text = token.decode("utf-8", "replace")
            if text == run_str or text.startswith(prefix):
                pids.append(pid)
                break
    return pids


def reap_run_processes(run_path: Path) -> int:
    """SIGKILL processes provably owned by `run_path` (see `run_owned_pids`).

    Best-effort (review MAJOR-2 B): a Nextflow local-executor task that
    detached into another session AND left the run dir (chdir elsewhere)
    with no run-path argument cannot be attributed and may survive — a
    documented hard limit, not silently claimed away."""
    reaped = 0
    for pid in run_owned_pids(run_path):
        try:
            os.kill(pid, signal.SIGKILL)
            reaped += 1
        except (ProcessLookupError, PermissionError):
            pass
    return reaped


class NextflowBackend(LocalReproductionRunner):
    """Runs a ReproductionCapsule through Nextflow, producing the same
    ExecutionReceipt shape as the WP5 local runner."""

    def __init__(self, backend: BackendIdentity | None = None) -> None:
        self._backend = backend
        self._version_cache: str | None = None

    # -- identity ----------------------------------------------------------- #

    def _backend_identity(self, binary: str) -> BackendIdentity:
        if self._version_cache is None:
            self._version_cache = _nextflow_version(binary)
        return BackendIdentity(kind="external", name="nextflow",
                               version=self._version_cache)

    # -- snapshot: ignore nextflow's own bookkeeping ------------------------ #

    @staticmethod
    def _snapshot_subtree(workdir: Path) -> dict[str, tuple[int, int]]:
        """Like the runner's snapshot, but pruning `.nextflow*` paths (the
        backend's own bookkeeping, not job output)."""
        snap: dict[str, tuple[int, int]] = {}
        for path in sorted(workdir.rglob("*")):
            if path.is_file() and not any(
                    part.startswith(".nextflow") for part in path.parts):
                st = path.stat()
                snap[path.relative_to(workdir).as_posix()] = (st.st_mtime_ns, st.st_size)
        return snap

    # -- main entry --------------------------------------------------------- #

    def run(self, capsule: ReproductionCapsule, capsule_root,
            timeout: float = 120.0, run_dir=None) -> ExecutionReceipt:
        """Execute `capsule` via a generated main.nf. Raises
        NextflowUnavailableError / CapsuleIntegrityError /
        UndeclaredOutputError (fail-visible); a job-side failure (nonzero
        exit, timeout) is recorded in the receipt with status
        failed/timeout instead of raised.

        ``run_dir``: caller-owned audit directory (never removed). When
        None, a private temp directory is created and cleaned up after the
        receipt is built. A caller-provided ``run_dir`` must be fresh:
        reusing an existing one raises FileExistsError at the staged copy
        (deliberate — the audit trail must never be overwritten)."""
        binary = nextflow_binary()
        if binary is None:
            raise NextflowUnavailableError(
                "nextflow binary not found (PATH, interpreter bin dir and "
                "PF tools dir checked); install the Nextflow launcher per "
                "docs/reports/V1_4_NEXTFLOW_CONFORMANCE_PROOF.md "
                "(curl -s https://get.nextflow.io -o nextflow && bash nextflow)")

        root = Path(capsule_root).resolve()
        if not root.is_dir():
            raise FileNotFoundError(f"capsule_root is not a directory: {root}")
        workdir = (root / capsule.cwd).resolve()
        if not workdir.is_dir():
            raise FileNotFoundError(f"capsule cwd is not a directory: {workdir}")
        self._verify_declared_refs(capsule, root)

        own_run_dir = run_dir is None
        run_path = Path(run_dir) if run_dir is not None else Path(
            tempfile.mkdtemp(prefix="pf-nextflow-"))
        try:
            return self._run_in(capsule, root, binary, run_path, timeout)
        finally:
            # PF-owned scratch only; a caller-provided run_dir is audit
            # evidence and stays on disk. The receipt is fully built before
            # this point (_run_in returns it), so cleanup never truncates
            # receipt data.
            if own_run_dir:
                shutil.rmtree(run_path, ignore_errors=True)

    # -- bounded teardown ---------------------------------------------------- #

    @staticmethod
    def _kill_wrapper_tree(proc: subprocess.Popen, run_path: Path) -> None:
        """SIGKILL the wrapper's whole process group first, then reap PF-owned
        stragglers that sat outside the group (Nextflow's local executor can
        start a task in its own session). Never touches processes that do not
        provably belong to `run_path`."""
        try:
            os.killpg(os.getpgid(proc.pid), signal.SIGKILL)
        except (ProcessLookupError, PermissionError):
            pass
        try:
            proc.wait(timeout=2.0)
        except subprocess.TimeoutExpired:
            pass
        reap_run_processes(run_path)

    @staticmethod
    def _drain_pipes(proc: subprocess.Popen) -> tuple[bytes, bytes, str]:
        """Bounded final `communicate` after a kill.

        Grandchildren that are NOT provably PF-owned can hold the inherited
        pipe ends open forever; hanging here would freeze the caller. After
        a grace period the pipes are closed and the receipt says so —
        capture loss is recorded, never hidden. Returns
        (stdout, stderr, receipt-note)."""
        try:
            stdout, stderr = proc.communicate(timeout=_DRAIN_GRACE)
            return stdout or b"", stderr or b"", ""
        except subprocess.TimeoutExpired:
            proc.stdout.close()
            proc.stderr.close()
            return b"", b"", ("; output capture incomplete "
                              "(pipe holders survived reaping)")

    def _run_in(self, capsule: ReproductionCapsule, root: Path, binary: str,
                run_path: Path, timeout: float) -> ExecutionReceipt:
        run_path.mkdir(parents=True, exist_ok=True)
        stage = run_path / "capsule"
        shutil.copytree(root, stage)
        stage_workdir = (stage / capsule.cwd).resolve()
        before = self._snapshot_subtree(stage_workdir)

        main_nf = run_path / "main.nf"
        main_nf.write_text(render_nextflow_script(capsule, stage_workdir),
                           encoding="utf-8")

        started = utcnow()
        cmd = [binary, "run", str(main_nf), "-ansi-log", "false"]
        # Own session so a timeout/KeyboardInterrupt can kill the whole
        # process group — nextflow spawns JVM children that must not
        # linger as orphans.
        proc = subprocess.Popen(cmd, cwd=run_path, stdout=subprocess.PIPE,
                                stderr=subprocess.PIPE, start_new_session=True)
        try:
            try:
                stdout, stderr = proc.communicate(timeout=timeout)
            except subprocess.TimeoutExpired:
                self._kill_wrapper_tree(proc, run_path)
                stdout, stderr, note = self._drain_pipes(proc)
                status, exit_code = "timeout", None
                failure_reason = f"timeout after {timeout}s{note}"
            else:
                status = "completed" if proc.returncode == 0 else "failed"
                exit_code = proc.returncode
                stdout, stderr = stdout or b"", stderr or b""
                failure_reason = None if proc.returncode == 0 else (
                    f"nextflow exited with code {proc.returncode}")
        except KeyboardInterrupt:
            # NIT-2: without this, Ctrl-C left the wrapper group running.
            self._kill_wrapper_tree(proc, run_path)
            self._drain_pipes(proc)
            raise
        finished = utcnow()

        outputs = self._collect_outputs(capsule, stage)
        self._check_undeclared(capsule, stage, stage_workdir, before)

        return ExecutionReceipt(
            receipt_id=f"rcpt-{uuid.uuid4().hex}",
            execution_id=f"exec-{uuid.uuid4().hex}",
            capsule_id=capsule.capsule_id,
            capsule_digest=capsule.capsule_digest,
            status=status,
            exit_code=exit_code,
            outputs=outputs,
            stdout_sha256=sha256(stdout).hexdigest(),
            stderr_sha256=sha256(stderr).hexdigest(),
            backend=self._backend_identity(binary),
            started_at=started,
            finished_at=finished,
            failure_reason=failure_reason,
        )
