"""Snakemake backend adapter for Reproduction Capsules (WP7, ROADMAP v1.3).

Thin adapter, same contract shape as the WP5 local runner:
ReproductionCapsule in -> ExecutionReceipt out. It generates ONE minimal
Snakefile in a private run directory (never inside the caller's capsule
directory), executes it with `snakemake --cores 1`, and maps the result to an
ExecutionReceipt whose backend identity is `external/snakemake/<version>`.

Design decisions (all fail-visible, none of them hidden):

- Capability honesty: if no `snakemake` binary is found (PATH, then the
  interpreter's own bin directory), `run` raises SnakemakeUnavailableError.
  There is no fake/partial mode.
- Staging: the capsule root is copied into the run directory and snakemake
  executes against the copy. The caller's tree is never modified — snakemake
  always writes a `.snakemake` metadata directory into its working directory,
  and a backend must not pollute the caller's capsule root with it. Output
  content hashes are identical because the staged inputs are byte-identical
  (declared refs are verified before staging).
- One rule per capsule. The Snakefile declares exactly the capsule's
  expected_outputs and runs exactly the capsule's command in `capsule_root /
  cwd`. No multi-rule orchestration, no Snakemake semantics in the core
  contract — the adapter maps, it does not orchestrate.
- `--forceall`: a receipt must prove that the command ran in THIS execution,
  not that cached outputs were fresh. The staged copy is fresh on every run
  anyway; the flag makes the guarantee explicit.
- `.snakemake` metadata is the backend's own bookkeeping, so the
  undeclared-output snapshot ignores it. Files the JOB writes outside
  expected_outputs are still flagged exactly as in the local runner.
- Same documented hard limits as the local runner: this is not a sandbox. A
  job that writes outside the workdir subtree, touches the network, or reads
  undeclared inputs elsewhere is not detected by the snapshot diff.
- Snakemake is NEVER PF's orchestrator. This module is a consumer of the
  capsule contract, not a workflow engine embedded in PF.
"""
from __future__ import annotations

import shlex
import shutil
import subprocess
import sys
import tempfile
import uuid
from hashlib import sha256
from pathlib import Path

from ..verification.contract import BackendIdentity
from .capsule import ExecutionReceipt, ReproductionCapsule, utcnow
from .runner import LocalReproductionRunner

_SNAKEFILE_HEADER = (
    "# Generated by paper_factory.reproduction.snakemake_backend (WP7).\n"
    "# One rule per ReproductionCapsule; do not edit by hand.\n"
)


class SnakemakeUnavailableError(RuntimeError):
    """No snakemake binary found (PATH or interpreter bin dir). Fail-visible."""


def snakemake_binary() -> str | None:
    """Resolve a snakemake executable, or None if unavailable.

    Honest capability probe: PATH first, then the bin directory of the
    running interpreter (a snakemake installed into PF's own venv is found
    even when the venv's bin dir is not on PATH)."""
    found = shutil.which("snakemake")
    if found:
        return found
    candidate = Path(sys.executable).parent / "snakemake"
    return str(candidate) if candidate.is_file() else None


def _snakemake_version(binary: str) -> str:
    proc = subprocess.run([binary, "--version"], capture_output=True,
                          timeout=30, check=False)
    if proc.returncode != 0:
        return "unknown"
    # `snakemake --version` prints the bare version, e.g. "9.27.0".
    return proc.stdout.decode("utf-8", "replace").strip().splitlines()[-1].strip()


def _snakefile_escape(text: str) -> str:
    """Escape a string for embedding in a double-quoted Snakefile string."""
    return text.replace("\\", "\\\\").replace('"', '\\"')


def render_snakefile(capsule: ReproductionCapsule) -> str:
    """Deterministic minimal Snakefile for one capsule.

    The shell command reproduces the local runner's working-directory
    semantics (`cd capsule.cwd` when cwd is not "."); output patterns are
    the capsule's expected_outputs verbatim (relative to the capsule root,
    which with `--directory <staged root>` is also the Snakefile's view).
    Sorting keeps generation deterministic regardless of capsule list
    order."""
    shell_cmd = " ".join(shlex.quote(a) for a in capsule.command)
    if capsule.cwd != ".":
        # `&&` is a shell operator: quote the operands, never the operator
        shell_cmd = f"cd {shlex.quote(capsule.cwd)} && {shell_cmd}"
    shell_cmd = _snakefile_escape(shell_cmd)

    lines = [_SNAKEFILE_HEADER.rstrip("\n"), "rule capsule_run:", "    output:"]
    for pattern in sorted(capsule.expected_outputs):
        lines.append(f'        "{_snakefile_escape(pattern)}",')
    lines.append("    shell:")
    lines.append(f'        "{shell_cmd}"')
    lines.append("")
    return "\n".join(lines)


class SnakemakeBackend(LocalReproductionRunner):
    """Runs a ReproductionCapsule through Snakemake, producing the same
    ExecutionReceipt shape as the WP5 local runner."""

    def __init__(self, backend: BackendIdentity | None = None) -> None:
        self._backend = backend
        self._version_cache: str | None = None

    # -- identity ----------------------------------------------------------- #

    def _backend_identity(self, binary: str) -> BackendIdentity:
        if self._version_cache is None:
            self._version_cache = _snakemake_version(binary)
        return BackendIdentity(kind="external", name="snakemake",
                               version=self._version_cache,
                               detail={"cores": 1})

    # -- snapshot: ignore snakemake's own metadata -------------------------- #

    @staticmethod
    def _snapshot_subtree(workdir: Path) -> dict[str, tuple[int, int]]:
        """Like the runner's snapshot, but pruning `.snakemake` directories
        (the backend's own bookkeeping, not job output)."""
        snap: dict[str, tuple[int, int]] = {}
        for path in sorted(workdir.rglob("*")):
            if path.is_file() and ".snakemake" not in path.parts:
                st = path.stat()
                snap[path.relative_to(workdir).as_posix()] = (st.st_mtime_ns, st.st_size)
        return snap

    # -- main entry --------------------------------------------------------- #

    def run(self, capsule: ReproductionCapsule, capsule_root,
            timeout: float = 120.0, run_dir=None) -> ExecutionReceipt:
        """Execute `capsule` via a generated Snakefile. Raises
        SnakemakeUnavailableError / CapsuleIntegrityError /
        UndeclaredOutputError (fail-visible); a job-side failure (nonzero
        exit, timeout) is recorded in the receipt with status
        failed/timeout instead of raising."""
        binary = snakemake_binary()
        if binary is None:
            raise SnakemakeUnavailableError(
                "snakemake binary not found (PATH and interpreter bin dir "
                "checked); install the 'snakemake' extra "
                "(pip install paper-factory[snakemake])")

        root = Path(capsule_root).resolve()
        if not root.is_dir():
            raise FileNotFoundError(f"capsule_root is not a directory: {root}")
        workdir = (root / capsule.cwd).resolve()
        if not workdir.is_dir():
            raise FileNotFoundError(f"capsule cwd is not a directory: {workdir}")
        self._verify_declared_refs(capsule, root)

        run_path = Path(run_dir) if run_dir is not None else Path(
            tempfile.mkdtemp(prefix="pf-snakemake-"))
        run_path.mkdir(parents=True, exist_ok=True)
        stage = run_path / "capsule"
        shutil.copytree(root, stage)
        stage_workdir = (stage / capsule.cwd).resolve()
        before = self._snapshot_subtree(stage_workdir)

        snakefile = run_path / "Snakefile"
        snakefile.write_text(render_snakefile(capsule), encoding="utf-8")

        started = utcnow()
        cmd = [binary, "--cores", "1", "--snakefile", str(snakefile),
               "--directory", str(stage), "--forceall"]
        try:
            proc = subprocess.run(cmd, cwd=run_path, capture_output=True,
                                  timeout=timeout, check=False)
            status = "completed" if proc.returncode == 0 else "failed"
            stdout, stderr, exit_code = proc.stdout, proc.stderr, proc.returncode
            failure_reason = None if proc.returncode == 0 else (
                f"snakemake exited with code {proc.returncode}")
        except subprocess.TimeoutExpired as exc:
            status, exit_code = "timeout", None
            stdout = exc.stdout or b""
            stderr = exc.stderr or b""
            failure_reason = f"timeout after {timeout}s"
        finished = utcnow()

        outputs = self._collect_outputs(capsule, stage)
        self._check_undeclared(capsule, stage, stage_workdir, before)

        return ExecutionReceipt(
            receipt_id=f"rcpt-{uuid.uuid4().hex}",
            execution_id=f"exec-{uuid.uuid4().hex}",
            capsule_id=capsule.capsule_id,
            capsule_digest=capsule.capsule_digest,
            status=status,
            exit_code=exit_code,
            outputs=outputs,
            stdout_sha256=sha256(stdout).hexdigest(),
            stderr_sha256=sha256(stderr).hexdigest(),
            backend=self._backend_identity(binary),
            started_at=started,
            finished_at=finished,
            failure_reason=failure_reason,
        )
