"""Snakemake backend adapter for Reproduction Capsules (WP7, ROADMAP v1.3).

Thin adapter, same contract shape as the WP5 local runner:
ReproductionCapsule in -> ExecutionReceipt out. It generates ONE minimal
Snakefile in a private run directory (never inside the caller's capsule
directory), executes it with `snakemake --cores 1`, and maps the result to an
ExecutionReceipt whose backend identity is `external/snakemake/<version>`.

Design decisions (all fail-visible, none of them hidden):

- Capability honesty: if no `snakemake` binary is found (PATH, then the
  interpreter's own bin directory), `run` raises SnakemakeUnavailableError.
  There is no fake/partial mode.
- Staging: the capsule root is copied into the run directory and snakemake
  executes against the copy. The caller's tree is never modified — snakemake
  always writes a `.snakemake` metadata directory into its working directory,
  and a backend must not pollute the caller's capsule root with it. Output
  content hashes are identical because the staged inputs are byte-identical
  (declared refs are verified before staging).
- One rule per capsule. The Snakefile declares exactly the capsule's
  expected_outputs and runs exactly the capsule's command in `capsule_root /
  cwd`. No multi-rule orchestration, no Snakemake semantics in the core
  contract — the adapter maps, it does not orchestrate. The shell string
  is escaped for Snakemake's format layer (`{`/`}` doubled, `\\`/`\"`
  backslash-escaped) so the job receives the capsule's exact argv
  (review MAJOR-1 B conformance case).
- `--forceall`: a receipt must prove that the command ran in THIS execution,
  not that cached outputs were fresh. The staged copy is fresh on every run
  anyway; the flag makes the guarantee explicit.
- `.snakemake` metadata is the backend's own bookkeeping, so the
  undeclared-output snapshot ignores it. Files the JOB writes outside
  expected_outputs are still flagged exactly as in the local runner.
- Run-directory lifecycle: when ``run_dir`` is not given, the backend
  creates a private ``pf-snakemake-*`` directory and removes it in a
  ``finally`` after the receipt is built (review B-MINOR-3, 2026-10-05) —
  no temp-directory leaks. A caller-provided ``run_dir`` is NEVER removed
  (it is the caller's audit trail; the staged copy inside it stays
  inspectable).
- exit_code semantics (review B-MINOR-4, documented, deferred): the
  receipt's ``exit_code`` is the WRAPPER's exit code — the ``snakemake``
  process itself. Snakemake exits nonzero when the job's shell command
  fails, but a job "succeeding" in snakemake's eyes while the capsule's
  real intent failed (wrong outputs written, silent in-shell failure
  patterns snakemake cannot see) is NOT separately captured: the capsule
  command runs inside snakemake's shell, its own exit status is not
  propagated into the receipt. The receipt's honest signals are the
  output content hashes plus status/failure_reason.
- Same documented hard limits as the local runner: this is not a sandbox. A
  job that writes outside the workdir subtree, touches the network, or reads
  undeclared inputs elsewhere is not detected by the snapshot diff.
- Snakemake is NEVER PF's orchestrator. This module is a consumer of the
  capsule contract, not a workflow engine embedded in PF.
"""
from __future__ import annotations

import os
import shlex
import shutil
import signal
import subprocess
import sys
import tempfile
import uuid
from hashlib import sha256
from pathlib import Path

from ..verification.contract import BackendIdentity
from .capsule import ExecutionReceipt, ReproductionCapsule, utcnow
from .runner import LocalReproductionRunner

_SNAKEFILE_HEADER = (
    "# Generated by paper_factory.reproduction.snakemake_backend (WP7).\n"
    "# One rule per ReproductionCapsule; do not edit by hand.\n"
)


class SnakemakeUnavailableError(RuntimeError):
    """No snakemake binary found (PATH or interpreter bin dir). Fail-visible."""


def snakemake_binary() -> str | None:
    """Resolve a snakemake executable, or None if unavailable.

    Honest capability probe: PATH first, then the bin directory of the
    running interpreter (a snakemake installed into PF's own venv is found
    even when the venv's bin dir is not on PATH)."""
    found = shutil.which("snakemake")
    if found:
        return found
    candidate = Path(sys.executable).parent / "snakemake"
    return str(candidate) if candidate.is_file() else None


def _snakemake_version(binary: str) -> str:
    proc = subprocess.run([binary, "--version"], capture_output=True,
                          timeout=30, check=False)
    if proc.returncode != 0:
        return "unknown"
    # `snakemake --version` prints the bare version, e.g. "9.27.0".
    return proc.stdout.decode("utf-8", "replace").strip().splitlines()[-1].strip()


def _snakefile_escape(text: str) -> str:
    """Escape a string for embedding in a double-quoted Snakefile string.

    Snakemake applies format-style substitution (`str.format` semantics) to
    shell commands and output strings: `{`/`}` must be doubled, `\\` and
    `\"` backslash-escaped. Same metacharacter class as the Nextflow
    GString interpolation (review MAJOR-1 B conformance case: without this,
    an argv element containing `${x}` failed the job with
    "The name 'x' is unknown in this context")."""
    return (text.replace("{", "{{").replace("}", "}}")
            .replace("\\", "\\\\").replace('"', '\\"'))


def render_snakefile(capsule: ReproductionCapsule) -> str:
    """Deterministic minimal Snakefile for one capsule.

    The shell command reproduces the local runner's working-directory
    semantics (`cd capsule.cwd` when cwd is not "."); output patterns are
    the capsule's expected_outputs verbatim (relative to the capsule root,
    which with `--directory <staged root>` is also the Snakefile's view).
    Sorting keeps generation deterministic regardless of capsule list
    order."""
    shell_cmd = " ".join(shlex.quote(a) for a in capsule.command)
    if capsule.cwd != ".":
        # `&&` is a shell operator: quote the operands, never the operator
        shell_cmd = f"cd {shlex.quote(capsule.cwd)} && {shell_cmd}"
    shell_cmd = _snakefile_escape(shell_cmd)

    lines = [_SNAKEFILE_HEADER.rstrip("\n"), "rule capsule_run:", "    output:"]
    for pattern in sorted(capsule.expected_outputs):
        lines.append(f'        "{_snakefile_escape(pattern)}",')
    lines.append("    shell:")
    lines.append(f'        "{shell_cmd}"')
    lines.append("")
    return "\n".join(lines)


class SnakemakeBackend(LocalReproductionRunner):
    """Runs a ReproductionCapsule through Snakemake, producing the same
    ExecutionReceipt shape as the WP5 local runner."""

    def __init__(self, backend: BackendIdentity | None = None) -> None:
        self._backend = backend
        self._version_cache: str | None = None

    # -- identity ----------------------------------------------------------- #

    def _backend_identity(self, binary: str) -> BackendIdentity:
        if self._version_cache is None:
            self._version_cache = _snakemake_version(binary)
        return BackendIdentity(kind="external", name="snakemake",
                               version=self._version_cache,
                               detail={"cores": 1})

    # -- snapshot: ignore snakemake's own metadata -------------------------- #

    @staticmethod
    def _snapshot_subtree(workdir: Path) -> dict[str, tuple[int, int]]:
        """Like the runner's snapshot, but pruning `.snakemake` directories
        (the backend's own bookkeeping, not job output)."""
        snap: dict[str, tuple[int, int]] = {}
        for path in sorted(workdir.rglob("*")):
            if path.is_file() and ".snakemake" not in path.parts:
                st = path.stat()
                snap[path.relative_to(workdir).as_posix()] = (st.st_mtime_ns, st.st_size)
        return snap

    # -- main entry --------------------------------------------------------- #

    def run(self, capsule: ReproductionCapsule, capsule_root,
            timeout: float = 120.0, run_dir=None) -> ExecutionReceipt:
        """Execute `capsule` via a generated Snakefile. Raises
        SnakemakeUnavailableError / CapsuleIntegrityError /
        UndeclaredOutputError (fail-visible); a job-side failure (nonzero
        exit, timeout) is recorded in the receipt with status
        failed/timeout instead of raising.

        ``run_dir``: caller-owned audit directory (never removed). When
        None, a private temp directory is created and cleaned up after the
        receipt is built. A caller-provided ``run_dir`` must be fresh:
        reusing an existing one raises FileExistsError at the staged copy
        (deliberate — the audit trail must never be overwritten). NOTE
        (B-MINOR-4): the receipt's exit_code is the
        snakemake WRAPPER's exit code, not the capsule command's own shell
        exit status — see the module docstring."""
        binary = snakemake_binary()
        if binary is None:
            raise SnakemakeUnavailableError(
                "snakemake binary not found (PATH and interpreter bin dir "
                "checked); install the 'snakemake' extra "
                "(pip install paper-factory[snakemake])")

        root = Path(capsule_root).resolve()
        if not root.is_dir():
            raise FileNotFoundError(f"capsule_root is not a directory: {root}")
        workdir = (root / capsule.cwd).resolve()
        if not workdir.is_dir():
            raise FileNotFoundError(f"capsule cwd is not a directory: {workdir}")
        self._verify_declared_refs(capsule, root)

        own_run_dir = run_dir is None
        # Resolve caller paths: a relative run_dir would reach snakemake as
        # a relative --snakefile/--directory path from a different working
        # directory and silently target the wrong tree. Receipt/staging
        # semantics are unchanged. (Same hardening as the Nextflow adapter.)
        run_path = (Path(run_dir).resolve() if run_dir is not None else Path(
            tempfile.mkdtemp(prefix="pf-snakemake-")))
        try:
            return self._run_in(capsule, root, binary, run_path, timeout)
        finally:
            # PF-owned scratch only; a caller-provided run_dir is audit
            # evidence and stays on disk. The receipt is fully built before
            # this point (_run_in returns it), so cleanup never truncates
            # receipt data.
            if own_run_dir:
                shutil.rmtree(run_path, ignore_errors=True)

    def _run_in(self, capsule: ReproductionCapsule, root: Path, binary: str,
                run_path: Path, timeout: float) -> ExecutionReceipt:
        run_path.mkdir(parents=True, exist_ok=True)
        stage = run_path / "capsule"
        shutil.copytree(root, stage)
        stage_workdir = (stage / capsule.cwd).resolve()
        before = self._snapshot_subtree(stage_workdir)

        snakefile = run_path / "Snakefile"
        snakefile.write_text(render_snakefile(capsule), encoding="utf-8")

        started = utcnow()
        cmd = [binary, "--cores", "1", "--snakefile", str(snakefile),
               "--directory", str(stage), "--forceall"]
        # Own session so a timeout/KeyboardInterrupt can kill the whole
        # process group (snakemake spawns job shells as children).
        proc = subprocess.Popen(cmd, cwd=run_path, stdout=subprocess.PIPE,
                                stderr=subprocess.PIPE, start_new_session=True)
        try:
            stdout, stderr = proc.communicate(timeout=timeout)
            status = "completed" if proc.returncode == 0 else "failed"
            stdout, stderr = stdout or b"", stderr or b""
            exit_code = proc.returncode
            failure_reason = None if proc.returncode == 0 else (
                f"snakemake exited with code {proc.returncode}")
        except subprocess.TimeoutExpired:
            try:
                os.killpg(os.getpgid(proc.pid), signal.SIGKILL)
            except (ProcessLookupError, PermissionError):
                pass
            try:
                stdout, stderr = proc.communicate(timeout=10.0)
            except subprocess.TimeoutExpired:
                proc.stdout.close()
                proc.stderr.close()
                stdout, stderr = b"", b""
            stdout, stderr = stdout or b"", stderr or b""
            status, exit_code = "timeout", None
            failure_reason = f"timeout after {timeout}s"
        except KeyboardInterrupt:
            # NIT-2: without this, Ctrl-C left the wrapper group running.
            try:
                os.killpg(os.getpgid(proc.pid), signal.SIGKILL)
            except (ProcessLookupError, PermissionError):
                pass
            try:
                proc.communicate(timeout=10.0)
            except subprocess.TimeoutExpired:
                proc.stdout.close()
                proc.stderr.close()
            raise
        finished = utcnow()

        outputs = self._collect_outputs(capsule, stage)
        self._check_undeclared(capsule, stage, stage_workdir, before)

        return ExecutionReceipt(
            receipt_id=f"rcpt-{uuid.uuid4().hex}",
            execution_id=f"exec-{uuid.uuid4().hex}",
            capsule_id=capsule.capsule_id,
            capsule_digest=capsule.capsule_digest,
            status=status,
            exit_code=exit_code,
            outputs=outputs,
            stdout_sha256=sha256(stdout).hexdigest(),
            stderr_sha256=sha256(stderr).hexdigest(),
            backend=self._backend_identity(binary),
            started_at=started,
            finished_at=finished,
            failure_reason=failure_reason,
        )
