"""P11 Tables: deterministic table plan and booktabs LaTeX tables derived
from reports/paper_metrics.json. Numbers always come from the metrics file,
never hand-typed. Output: paper/generated/tables.tex +
reports/tables_manifest.json.
"""
from __future__ import annotations

from pathlib import Path
from typing import Any

from ..core.results import Verdict
from ..core.util import read_json, sha256_file, utcnow, write_json
from ..dag.executor import NodeContext, NodeOutcome

_SOURCE_SCRIPT = "paper_factory/tables/build.py"


def _fmt(value: Any) -> str:
    if value is None:
        return "--"
    if isinstance(value, bool):
        return str(value)
    if isinstance(value, int):
        return str(value)
    return f"{float(value):.6g}"


def _tex_escape(text: str) -> str:
    return text.replace("_", "\\_")


def _table_id(source: str) -> str:
    return f"tab_{Path(source).stem}".replace("-", "_")


def _table_label(source: str) -> str:
    return f"tab:{Path(source).stem}".replace("-", "_")


def run_table_plan(ctx: NodeContext) -> NodeOutcome:
    """Plan one table per metrics source (rows = metrics of that source,
    columns n/mean/std/CI95 where present)."""
    metrics_path = ctx.workspace.reports_dir / "paper_metrics.json"
    if not metrics_path.exists():
        # honest degradation, not a hard failure: with no derived metrics
        # there is nothing to tabulate — recorded, not blocking
        return NodeOutcome(Verdict.DEGRADED,
                           {"reason": "no paper_metrics.json — no tables derivable"})
    doc = read_json(metrics_path)
    metrics: dict[str, Any] = doc.get("metrics") or {}
    if not metrics:
        return NodeOutcome(Verdict.DEGRADED,
                           {"reason": "paper_metrics.json has no metrics — no tables derivable"})
    plan: dict[str, Any] = {"planned_at": utcnow(), "metrics_sha256": sha256_file(metrics_path),
                            "tables": []}

    by_source: dict[str, list[str]] = {}
    for key in sorted(metrics):
        by_source.setdefault(metrics[key]["source"], []).append(key)

    for source in sorted(by_source):
        keys = by_source[source]
        columns = ["n", "mean"]
        if any(metrics[k].get("std") is not None for k in keys):
            columns.append("std")
        if any(metrics[k].get("ci95_halfwidth") is not None for k in keys):
            columns.append("ci95_halfwidth")
        plan["tables"].append({
            "table_id": _table_id(source),
            "label": _table_label(source),
            "source": source,
            "metric_keys": keys,
            "columns": columns,
            "caption": (f"Aggregated results from {_tex_escape(source)}; all values generated "
                        f"by the statistics pipeline (n = seeds per group)."),
        })

    write_json(ctx.workspace.reports_dir / "table_plan.json", plan)
    if not plan["tables"]:
        return NodeOutcome(Verdict.DEGRADED, {"reason": "no metrics to tabulate"})
    return NodeOutcome(Verdict.PASS, {"tables": len(plan["tables"])})


def _render_table(table: dict[str, Any], metrics: dict[str, Any]) -> str:
    col_headers = {"n": "$n$", "mean": "Mean", "std": "Std", "ci95_halfwidth": "CI95 half-width"}
    lines = [
        "\\begin{table}[htbp]",
        "  \\centering",
        f"  \\caption{{{table['caption']}}}",
        f"  \\label{{{table['label']}}}",
        f"  \\begin{{tabular}}{{{'l' + 'r' * len(table['columns'])}}}",
        "    \\toprule",
        "    Metric & " + " & ".join(col_headers[c] for c in table["columns"]) + " \\\\",
        "    \\midrule",
    ]
    for key in table["metric_keys"]:
        m = metrics[key]
        cells = [_fmt(m.get(c)) for c in table["columns"]]
        lines.append(f"    \\texttt{{{_tex_escape(m['field'])}}} & " + " & ".join(cells) + " \\\\")
    lines += [
        "    \\bottomrule",
        "  \\end{tabular}",
        "\\end{table}",
    ]
    return "\n".join(lines)


def _write_empty_tables_tex(ctx: NodeContext, why: str) -> None:
    """GAP-2 (real pilot 2): a DEGRADED table node still emits a VALID empty
    tables.tex (provenance header, zero tables) — the manuscript scaffold
    references generated/tables.tex unconditionally."""
    gen = ctx.workspace.paper_dir / "generated"
    gen.mkdir(parents=True, exist_ok=True)
    (gen / "tables.tex").write_text(
        "% generated by paper-factory tables — do not hand-edit\n"
        f"% empty by design: {why}\n", encoding="utf-8")


def run_table_generation(ctx: NodeContext) -> NodeOutcome:
    """Render the planned tables as booktabs LaTeX into
    paper/generated/tables.tex plus reports/tables_manifest.json."""
    plan_path = ctx.workspace.reports_dir / "table_plan.json"
    metrics_path = ctx.workspace.reports_dir / "paper_metrics.json"
    if not plan_path.exists():
        _write_empty_tables_tex(ctx, "no table_plan.json — planning degraded upstream")
        return NodeOutcome(Verdict.DEGRADED,
                           {"reason": "no table_plan.json — planning degraded upstream"})
    if not metrics_path.exists():
        _write_empty_tables_tex(ctx, "no paper_metrics.json — nothing to render")
        return NodeOutcome(Verdict.DEGRADED,
                           {"reason": "no paper_metrics.json — nothing to render"})
    plan = read_json(plan_path)
    metrics: dict[str, Any] = (read_json(metrics_path).get("metrics")) or {}
    tables: list[dict[str, Any]] = plan.get("tables") or []
    if not tables:
        _write_empty_tables_tex(ctx, "table plan is empty — nothing to render")
        return NodeOutcome(Verdict.DEGRADED, {"reason": "table plan is empty — nothing to render"})

    chunks = ["% generated by paper-factory tables — do not hand-edit"]
    manifest: dict[str, Any] = {
        "generated_at": utcnow(),
        "source_script": _SOURCE_SCRIPT,
        "input_data_hashes": {"reports/paper_metrics.json": sha256_file(metrics_path)},
        "tables": [],
    }
    missing = [t["table_id"] for t in tables
               if any(k not in metrics for k in t["metric_keys"])]
    if missing:
        return NodeOutcome(Verdict.FAIL, {"reason": "planned metric keys missing from metrics",
                                          "tables": missing})
    for t in tables:
        chunks.append(_render_table(t, metrics))
        manifest["tables"].append({
            "table_id": t["table_id"], "label": t["label"], "source": t["source"],
            "metric_keys": t["metric_keys"], "columns": t["columns"],
            "caption": t["caption"],
        })

    gen = ctx.workspace.paper_dir / "generated"
    gen.mkdir(parents=True, exist_ok=True)
    out = gen / "tables.tex"
    out.write_text("\n\n".join(chunks) + "\n", encoding="utf-8")
    manifest["output"] = {"path": "paper/generated/tables.tex",
                          "sha256": sha256_file(out), "bytes": out.stat().st_size}
    write_json(ctx.workspace.reports_dir / "tables_manifest.json", manifest)
    return NodeOutcome(Verdict.PASS, {"tables": len(manifest["tables"]),
                                      "output": manifest["output"]["path"]})
