"""P09 Statistics: derive paper metrics from raw artifacts, never hand-typed.

Chain: raw (results/*.csv) → normalized → analysis → paper_metrics.json →
LaTeX macros (paper/generated/numbers.tex). Also computes the statistical
audit facts (n, std, CI, missing data) that reviews and closure rely on.
"""
from __future__ import annotations

import csv
import json
import math
import statistics
from pathlib import Path
from typing import Any

from ..core.results import Verdict
from ..core.util import sha256_file, utcnow, write_json
from ..dag.executor import NodeContext, NodeOutcome


def _mean_ci(values: list[float]) -> dict[str, Any]:
    n = len(values)
    mean = statistics.fmean(values)
    if n < 2:
        return {"n": n, "mean": mean, "std": None, "ci95": None,
                "note": "n<2: no spread estimable"}
    std = statistics.stdev(values)
    se = std / math.sqrt(n)
    # t-based CI with normal approximation fallback (small-n honesty: flagged)
    ci = 1.96 * se
    return {"n": n, "mean": mean, "std": std, "se": se, "ci95_halfwidth": ci,
            "small_sample": n < 5,
            "note": "normal-approx CI; n<5 flagged small_sample" if n < 5 else "normal-approx CI"}


def _load_csv(path: Path) -> tuple[list[str], list[dict[str, str]]]:
    with open(path, newline="", encoding="utf-8") as fh:
        reader = csv.DictReader(fh)
        return list(reader.fieldnames or []), list(reader)


def run_statistics(ctx: NodeContext) -> NodeOutcome:
    root = ctx.workspace.target_root
    results_dir = root / "results"
    if not results_dir.is_dir():
        return NodeOutcome(Verdict.DEGRADED, {"reason": "no results/ directory — no metrics derivable"})

    metrics: dict[str, Any] = {"computed_at": utcnow(), "sources": {}, "metrics": {},
                               "audit": {"missing_cells": 0, "exclusions": [],
                                         "small_samples": [], "randomization": "recorded_in_source",
                                         "grouping": "per design-parameter group (never pooled across loads/filters)"}}
    macro_lines = ["% generated by paper-factory statistics — do not hand-edit",
                   "\\makeatletter",
                   "\\newcommand{\\pfget}[1]{\\ifcsname pf@#1\\endcsname"
                   "\\csname pf@#1\\endcsname\\else\\textbf{??}\\fi}",
                   "\\makeatother"]

    def is_float(s: str) -> bool:
        try:
            float(s)
            return True
        except ValueError:
            return False

    for csv_path in sorted(results_dir.glob("*.csv")):
        fields, rows = _load_csv(csv_path)
        src_key = str(csv_path.relative_to(root))
        metrics["sources"][src_key] = {"sha256": sha256_file(csv_path), "rows": len(rows)}
        numeric_fields = [f for f in fields if rows and all(is_float((r.get(f) or "").strip())
                                                            for r in rows if (r.get(f) or "").strip())]
        # identifier columns (unique per row, e.g. run_id) are never group keys
        text_fields = [f for f in fields
                       if f not in numeric_fields and 1 < len({r.get(f, "") for r in rows}) <= 12]
        # design parameters: numeric with low cardinality (load, …) but not seeds
        design_nums = [f for f in numeric_fields
                       if f.lower() not in ("seed",) and 1 < len({r[f] for r in rows}) <= 12]
        group_cols = text_fields + design_nums
        outcome_fields = [f for f in numeric_fields if f not in design_nums
                          and f.lower() not in ("seed", "iteration", "run", "n")]

        groups: dict[tuple, list[dict[str, str]]] = {}
        for r in rows:
            key = tuple(r.get(c, "") for c in group_cols)
            groups.setdefault(key, []).append(r)

        for gkey, grows in sorted(groups.items()):
            gname = "__".join(f"{c}{v}" for c, v in zip(group_cols, gkey) if c)
            for f in outcome_fields:
                vals = []
                for r in grows:
                    cell = (r.get(f) or "").strip()
                    if not cell:
                        metrics["audit"]["missing_cells"] += 1
                        continue
                    vals.append(float(cell))
                if not vals:
                    continue
                stat = _mean_ci(vals)
                key = f"{csv_path.stem}__{f}" + (f"__{gname}" if gname else "")
                key = key.replace("-", "_").replace(".", "p")
                metrics["metrics"][key] = {"source": src_key, "field": f,
                                           "group": dict(zip(group_cols, gkey)), **stat}
                if stat.get("small_sample"):
                    metrics["audit"]["small_samples"].append(key)
                safe = key.replace("_", "")
                macro_lines.append(f"\\expandafter\\gdef\\csname pf@{safe}mean\\endcsname{{{stat['mean']:.6g}}}")
                if stat.get("std") is not None:
                    macro_lines.append(f"\\expandafter\\gdef\\csname pf@{safe}std\\endcsname{{{stat['std']:.6g}}}")
                macro_lines.append(f"\\expandafter\\gdef\\csname pf@{safe}n\\endcsname{{{stat['n']}}}")

    if not metrics["metrics"]:
        return NodeOutcome(Verdict.DEGRADED, {"reason": "no numeric outcome fields found",
                                              "sources": metrics["sources"]})

    write_json(ctx.workspace.reports_dir / "paper_metrics.json", metrics)
    gen = ctx.workspace.paper_dir / "generated"
    gen.mkdir(parents=True, exist_ok=True)
    (gen / "numbers.tex").write_text("\n".join(macro_lines) + "\n", encoding="utf-8")
    return NodeOutcome(Verdict.PASS, {"metric_count": len(metrics["metrics"]),
                                      "small_samples": metrics["audit"]["small_samples"]})


def run_integrity_audit(ctx: NodeContext) -> NodeOutcome:
    """P05: cross-check numbers asserted in drafts against derived metrics.

    Two deterministic checks:
    1. significance_without_test — 'p < x' / 'significant' claims with no
       computed statistical test artifact (MAJOR).
    2. number_mismatch — a draft decimal in the *range* of a derived metric
       (0.5x–2x) but >5% off from every metric: close enough to be a misquote.
       Significance contexts (p < …) are excluded from the number scan.
    """
    import re

    root = ctx.workspace.target_root
    metrics_path = ctx.workspace.reports_dir / "paper_metrics.json"
    findings: list[dict[str, Any]] = []
    drafts = sorted(root.glob("draft/*.md")) + sorted(root.glob("draft/*.tex"))

    sig_pat = re.compile(r"(p\s*[<≤=]\s*0?\.\d+|statistically significant|significant\b)",
                         re.I)
    num_pat = re.compile(r"\b0?\.\d{2,}\b")

    metrics: dict[str, Any] = {}
    true_values: dict[str, float] = {}
    has_test_artifact = False
    if metrics_path.exists():
        metrics = json.loads(metrics_path.read_text(encoding="utf-8")).get("metrics", {})
        true_values = {k: v["mean"] for k, v in metrics.items()}
        has_test_artifact = any(
            "test" in k.lower() or "pvalue" in k.lower() for k in true_values)

    for d in drafts:
        text = d.read_text(encoding="utf-8", errors="replace")
        sig_spans = [m.span() for m in sig_pat.finditer(text)]
        if sig_spans and not has_test_artifact:
            for sp in sig_spans:
                findings.append({
                    "severity": "MAJOR", "kind": "significance_without_test",
                    "draft": str(d.relative_to(root)), "span": list(sp),
                    "excerpt": text[max(0, sp[0] - 60):sp[1] + 40].strip()[:160],
                    "note": "significance claimed; no statistical test artifact exists",
                })
        for m in num_pat.finditer(text):
            if any(sp[0] - 12 <= m.start() <= sp[1] + 2 for sp in sig_spans):
                continue  # part of a p-value expression, not a result number
            val = float(m.group(0))
            if not true_values:
                continue
            decimals = len(m.group(0).split(".")[1]) if "." in m.group(0) else 0
            round_unit = 0.5 * 10 ** (-decimals)  # rounding unit of the printed value

            def matches(t: float) -> bool:
                tol = max(0.05 * abs(t), round_unit)  # 5% or print-rounding, whichever is looser
                return abs(val - t) <= tol

            if any(matches(t) for t in true_values.values()):
                continue  # matches a metric within tolerance
            in_range = [k for k, t in true_values.items()
                        if t and 0.5 * abs(t) <= abs(val) <= 2.0 * abs(t)]
            if in_range:
                closest = min(true_values, key=lambda k: abs(true_values[k] - val))
                findings.append({
                    "severity": "MAJOR", "kind": "number_mismatch",
                    "draft": str(d.relative_to(root)), "value": val,
                    "closest_metric": closest, "true_value": true_values[closest],
                    "note": "draft number within metric range but off every derived metric "
                            "(tolerance: 5% or print rounding unit)",
                })
    report = {"audited_at": utcnow(), "findings": findings,
              "drafts_checked": [str(d.relative_to(root)) for d in drafts]}
    write_json(ctx.workspace.reports_dir / "integrity_audit.json", report)
    # The audit PASSes when it executed completely; findings carry the red and
    # flow into reviews (P23–P26) and closure (U2/U5), which is where blocking
    # happens — after remediation (P27) had its chance.
    return NodeOutcome(Verdict.PASS, {"findings": len(findings),
                                      "kinds": sorted({f["kind"] for f in findings})})
